# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-08 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190308_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverifyrecord',
            old_name='sen_time',
            new_name='send_time',
        ),
    ]
